version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.12'
  commands:
    - pip install uv
    - uv sync --frozen --all-extras
    - uv run mkdocs build -f demo/mkdocs/config.yaml
    - uv run sphinx-apidoc -f -e -T -o=docs/api/ ./oembedpy
    - uv run sphinx-build -b dirhtml docs $READTHEDOCS_OUTPUT/html

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
