version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.6.0'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: ''
      SPHINX_SOURCE_DIR: 'docs'
      SPHINX_OUTPUT_DIR: 'build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras --all-groups'
      - 'lefthook install'
  verify:
    desc: 'Verify environment by all procs'
    cmds:
      - 'lefthook run pre-commit --all-files'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-extras' # To write out as lock-file
